site_name: Lady C
site_url: https://haiyuanzhou-byte.github.io/lady-c/
theme:
  name: material
  language: zh
  palette:
    scheme: default
  favicon: img/favicon.png

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - 主页: index.md
  - 经验贴: experience/index.md
  - 友链: friends/index.md
  - 关于: about/index.md
